name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 11', 'platform=tvOS Simulator,name=Apple TV', 'platform=OS X,arch=x86_64']

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild clean test -project Churnfighter.xcodeproj -scheme ChurnFighter-Package -destination "${destination}"
      env:
          destination: ${{ matrix.destination }}
